name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      UV_PUBLISH_TOKEN: ${{ secrets.PYPI_PAT_SECRET }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - run: uv sync --all-extras --no-cache --upgrade
      - run: uv build
      - name: Publish package with token
        if: ${{ env.UV_PUBLISH_TOKEN != '' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ env.UV_PUBLISH_TOKEN }}

      - name: Publish package with trusted publishing
        if: ${{ env.UV_PUBLISH_TOKEN == '' }}
        uses: pypa/gh-action-pypi-publish@release/v1
