# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        python_version: ['3.10', '3.11', '3.12']
        os: [ubuntu-latest, macOS-latest]  # TODO: windows-latest

    steps:
    - uses: actions/checkout@v4
   
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install dependencies with uv
      run: |
        uv venv && uv sync --all-extras --dev

    - name: Run Tests
      run: |
        source .venv/bin/activate && python tests.py
